server:
  port: 8086

spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.195.131
    virtual-host: /leyou
    username: leyou
    password: leyou

leyou:
  sms:
    accessKeyId: LTAItNxtDfk7MJMq # 你自己的accessKeyId
    accessKeySecret: HKUIDl21ZM7XoubErXjUFJq84dha8W # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称
