server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql:///hm49?useUnicode=yes&characterEncoding=utf8
    username: root
    password: root
  rabbitmq:
    host: 192.168.195.131
    virtual-host: /leyou
    username: leyou
    password: leyou
  redis:
    host: 192.168.195.131

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15

mybatis:
  type-aliases-package: com.leyou.user.pojo